import pygame
pygame.init()

ntuMap = pygame.image.load('./img/ntuu.jpg')
yesButton = pygame.image.load('./img/yes.jpg')
noButton = pygame.image.load('./img/no.jpg')
opening = pygame.image.load('./img/opening.png')
whereAreYou = pygame.image.load('./img/whereAreYou.png')
foodCriteria = pygame.image.load('./img/foodCriteria.png')
halal = pygame.image.load('./img/halal.png')
veg = pygame.image.load('./img/veg.png')
none = pygame.image.load('./img/none.png')
background = pygame.image.load('./img/background.jpg')
sortByDistance = pygame.image.load('./img/sortByDistance.png')
sortByRank = pygame.image.load('./img/sortByRank.png')
searchByFood = pygame.image.load('./img/searchTheFood.png')
searchByPrice = pygame.image.load('./img/searchByPrice.png')
plusRange = pygame.image.load('./img/plus.png')
minusRange = pygame.image.load('./img/min.png')
numBox = pygame.image.load('./img/number.png')
submit = pygame.image.load('./img/submit.png')
foodPict = pygame.image.load('./img/food.png')
empty = pygame.image.load('./img/empty.png')
canteen_name = pygame.image.load('./img/canteen_name.png')
user = pygame.image.load('./img/user.png')
nextButton = pygame.image.load('./img/next.png')